packages:
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - unrs-resolver

nodeLinker: node-modules

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@swc/core'
  - bcrypt
  - esbuild
  - prisma
