name: finora-client

on:
  push:
    branches: [ main, dev ]
    paths:
      - "packages/client/**"
  pull_request:
    branches: [ main, dev ]
    paths:
      - "packages/client/**"

jobs:
  security-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ------------------------
      # 🐳 Docker Setup
      # ------------------------
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_FRONT }}
          password: ${{ secrets.DOCKERHUB_TOKEN_FRONT }}

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Define Docker image tags
        shell: bash
        run: |
          IMAGE="${{ secrets.DOCKERHUB_USERNAME_FRONT }}/finora-front"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          echo "TAG1=$IMAGE:${GITHUB_REF_NAME}" >> $GITHUB_ENV

          SHORT_SHA="${GITHUB_SHA::7}"
          echo "TAG2=$IMAGE:${GITHUB_REF_NAME}-$SHORT_SHA" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/client
          push: true
          tags: |
            ${{ env.TAG1 }}
            ${{ env.TAG2 }}
          build-args: |
            BRANCH=${{ env.BRANCH }}